=== devKaos117/Olympus.py/olympus/modules/polyhymnia/config/similarity.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://github.com/devKaos117/Olympus.py/blob/main/olympus/modules/polyhymnia/config/similarity.schema.json",
	"title": "polyhymnia.Similarity config schema",
	"description": "Configuration dictionary to polyhymnia Similarity engine",
	"type": "object",
	"properties": {
		"levenshtein": {
			"description": "",
			"type": "object",
			"properties": {
				"substitution": {
					"description": "",
					"type": "integer"
				},
				"insertion": {
					"description": "",
					"type": "integer"
				},
				"deletion": {
					"description": "",
					"type": "integer"
				}
			},
			"required": ["substitution", "insertion", "deletion"]
		},
		"jaro_winkler": {
			"description": "",
			"type": "object",
			"properties": {
				"prefix_scale": {
					"description": "",
					"type": "number"
				}
			},
			"required": ["prefix_scale"]
		},
		"ngram": {
			"description": "",
			"type": "object",
			"properties": {
				"n": {
					"description": "",
					"type": "integer",
					"minimum": 2
				}
			},
			"required": ["n"]
		},
		"jaccard": {
			"description": "",
			"type": "object",
			"properties": {
				"stop_words": {
					"description": "",
					"type": "array",
					"items": {
						"type": "string"
					}
				}
			},
			"required": ["stop_words"]
		},
		"abbreviation": {
			"description": "",
			"type": "object",
			"properties": {
				"strict_mode": {
					"description": "",
					"type": "boolean"
				}
			},
			"required": ["strict_mode"]
		},
		"weights": {
			"description": "",
			"type": "object",
			"properties": {
				"levenshtein": { "type": "number" },
				"jaro_winkler": { "type": "number" },
				"ngram": { "type": "number" },
				"abbreviation": { "type": "number" },
				"jaccard": { "type": "number" },
				"sequence_matcher": { "type": "number" }
			},
			"required": ["levenshtein", "jaro_winkler", "ngram", "abbreviation", "jaccard", "sequence_matcher"]
		}
	},
	"required": ["levenshtein", "jaro_winkler", "ngram", "jaccard", "abbreviation", "weights"]
}

=== devKaos117/Olympus.py/olympus/config/polyhymnia.similarity.json
{
    "levenshtein": {
        "substitution": 1,
        "insertion": 1,
        "deletion": 1
    },
    "jaro_winkler": {
        "prefix_scale": 0.1
    },
    "ngram": {
        "n": 2
    },
    "jaccard": {
        "stop_words": ["a", "an", "and", "are", "as", "at", "be", "by", "for", "from", "has", "he", "in", "is", "it", "its", "of", "on", "that", "the", "to", "was", "will", "with", "or", "but", "not", "no", "yes", "i", "you", "we", "they", "she", "him", "her", "his", "this", "these", "those", "them", "there", "their", "what", "when","where", "who", "why", "how", "all", "any", "both", "each", "few", "more", "most", "other", "some", "such", "only", "own","same", "so", "than", "too", "very", "can", "could", "should", "would", "have", "had", "been", "being", "do", "does", "did","am", "is", "are", "was", "were"]
    },
    "abbreviation": {
        "strict_mode": false
    },
    "weights": {
        "levenshtein": 1,
        "jaro_winkler": 1,
        "ngram": 1,
        "jaccard": 1,
        "abbreviation": 1,
        "sequence_matcher": 1
    }
}
